version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    privileged: true
    user: "${JENKINS_USER_ID}:${JENKINS_GROUP_ID}"
    ports:
      - "8080:8080"
      - "50000:50000"
    container_name: jenkins-local
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_GID=${JENKINS_GROUP_ID}
    group_add:
      - "${JENKINS_GROUP_ID}"
